#! /bin/bash
chmod 644 /usr/lib/udev/rules.d/99-makerbase-automount.rules
chmod 644 /usr/lib/systemd/system/makerbase-automount@.service
chmod 644 /etc/makerbase-automount.d/*
chmod 777 /usr/bin/makerbase-automount
chmod 777 /usr/bin/umount_dmenu
systemctl stop moonraker.service
if [ -f /home/mks/printer_data/database/data.mdb ]; then rm /home/mks/printer_data/database/data.mdb; fi
systemctl start moonraker.service


USERNAME=sovol
if id -u ${USERNAME} >/dev/null 2>&1 ; then
    echo "User ${USERNAME} exists."
else
    useradd -d /home/sovol -g netdev -m sovol
fi

chmod 777 /root/auto_refresh
chgrp netdev /home/mks/ -R
chown mks /home/mks/ -R

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS="$*"

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="5.16.20-rockchip64" --arg="/boot/vmlinuz-5.16.20-rockchip64" /etc/kernel/postinst.d

ln -sf vmlinuz-5.16.20-rockchip64 /boot/Image 2> /dev/null || mv /boot/vmlinuz-5.16.20-rockchip64 /boot/Image
touch /boot/.next
exit 0



